export const theme = {
  colors: {
    primary: '#6C63FF',
    primaryDark: '#4F46E5',
    primarySoft: '#A5B4FC',
    accent: '#8B5CF6',
    accentLight: '#DDD6FE',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceElevated: '#F1F5F9',
    text: '#1E293B',
    textSecondary: '#475569',
    textMuted: '#94A3B8',
    border: '#E2E8F0',
    divider: '#F1F5F9',
    income: '#10B981',
    incomeLight: '#D1FAE5',
    incomeDark: '#065F46',
    expense: '#EF4444',
    expenseLight: '#FEE2E2',
    expenseDark: '#991B1B',
    warning: '#F59E0B',
    warningLight: '#FEF3C7',
    info: '#3B82F6',
    infoLight: '#DBEAFE',
    success: '#10B981',
    successLight: '#D1FAE5',
    shadow: 'rgba(0,0,0,0.08)',
    overlay: 'rgba(0,0,0,0.5)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    full: 9999,
  },
  typography: {
    hero: {
      fontSize: 36,
      fontWeight: '800' as const,
      letterSpacing: -1,
      lineHeight: 44,
    },
    title: {
      fontSize: 22,
      fontWeight: '700' as const,
      letterSpacing: -0.5,
      lineHeight: 28,
    },
    heading: {
      fontSize: 18,
      fontWeight: '600' as const,
      letterSpacing: -0.3,
      lineHeight: 24,
    },
    subtitle: {
      fontSize: 14,
      fontWeight: '500' as const,
      letterSpacing: 0,
      lineHeight: 20,
    },
    body: {
      fontSize: 15,
      fontWeight: '400' as const,
      letterSpacing: 0,
      lineHeight: 22,
    },
    label: {
      fontSize: 13,
      fontWeight: '500' as const,
      letterSpacing: 0.2,
      lineHeight: 18,
    },
    caption: {
      fontSize: 12,
      fontWeight: '400' as const,
      letterSpacing: 0.1,
      lineHeight: 16,
    },
    tiny: {
      fontSize: 10,
      fontWeight: '500' as const,
      letterSpacing: 0.5,
      lineHeight: 14,
    },
  },
  shadow: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 8,
    },
  },
};
